name: Run Tests on Pull Request

on:
  pull_request:
    branches:
      - main 

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'

      - name: Restore dependencies
        run: dotnet restore src/ApiContactos.sln

      - name: Build the project
        run: dotnet build src/ApiContactos.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test src/ApiContactos.sln --no-build --configuration Release --logger "trx;LogFileName=test-results.trx"
